language: cpp
compiler:
  - clang
  - gcc
os:
  - linux
addons:
 apt:
   update: true
   sources:
     - ubuntu-toolchain-r-test
   packages:
   - "pkg-config"
   - "python3"
   - "python3-dev"
   - "python3-yaml"
   - "python3-wheel"
   - "python3-setuptools"
   - "python3-cryptography"
   - "python3-pip"
   - gcc-7
   - g++-7
   - cmake
   - doxygen
   - libc6-dbg  # needed by Valgrind
   - valgrind
   - ggcov
   - lcov
   - curl
 coverity_scan:
  project:
      name: "abbyssoul/libstyxe"
      description: "9P2000 protocol implementation"
  notification_email: abbyssoul@gmail.com
  build_command: make
  branch_pattern: coverity_scan

before_install:
  - sudo -H pip3 install --upgrade pip
  - sudo -H pip3 install cpplint cpp-coveralls
  - sudo -H pip3 install conan --upgrade
  - gem install coveralls-lcov

install:
  - gcov --version
  - lcov --version
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 90 --slave /usr/bin/g++ g++ /usr/bin/g++-7
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-7 90
  - echo $CXX
  - $CXX --version
  - ld --version
  - conan --version
  - conan profile new default --detect
  - conan profile update settings.compiler.libcxx=libstdc++11 default
  - conan remote add abbyssoul https://api.bintray.com/conan/abbyssoul/public-conan

script:
  - ./configure --enable-sanitizer
  - if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then make clean codecheck; fi
  - if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then make test; fi
  - if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then ./configure --disable-sanitizer --enable-debug && make clean && make verify ; fi

after_success:
  - make clean coverage_report
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
  - coveralls-lcov --repo-token ${COVERALLS_TOKEN} coverage.info  # uploads to coveralls
